<?php /** @var Elegento\Instagram\Block\Widget\Instagram $block */ ?>

<?php /** @var Elegento\Instagram\Helper\Data $helper */ ?>
<?php $helper = $this->helper('Elegento\Instagram\Helper\Data') ?>

<?php if($block->getData('title')): ?>
    <div id="instagram-slider">
        <h2><?= $block->escapeHtml($block->getData('title')) ?></h2>
        <div  class="slick-instagram-slider">
            <?php foreach ($block->getInstagramCollection() as $item) : ?>
                <div class="item">
                    <a target="_blank" href="<?= $block->escapeUrl($item->getPostLink()) ?>">
                        <img src="<?= $block->escapeUrl($item->getUploadedImageUrl() ?: $item->getImageUrl()) ?>" alt="<?= $block->escapeHtmlAttr($item->getPostCaption()) ?>"/>
                    </a>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
<?php endif; ?>

<script>
    require([
        'jquery',
        'slick'
    ], function ($) {

        'use strict';

        $(".slick-instagram-slider").slick(
            {
                dots: <?= $block->escapeJs($helper->slickDots()) ?>,
                arrows: <?= $block->escapeJs($helper->slickArrows()) ?>,
                infinite: true,
                speed: 1000,
                slidesToShow: 6,
                slidesToScroll: 4,
                autoplay: true,
                autoplaySpeed: 4000,
                responsive: [
                    {
                        breakpoint: 1024,
                        settings: {
                            slidesToShow: 4,
                        }
                    },
                    {
                        breakpoint: 768,
                        settings: {
                            slidesToShow: 3,
                        }
                    }
                ]
            }
        );
    });
</script>
