<?php /** @var Elegento\Instagram\Block\Widget\Instagram $block */ ?>

<?php /** @var Elegento\Instagram\Helper\Data $helper */ ?>
<?php $helper = $this->helper('Elegento\Instagram\Helper\Data') ?>

<?php if($block->getData('title')): ?>
    <div id="instagram-slider">
        <h2>
            <a target="blank" href="<?= $block->escapeUrl('https://www.instagram.com/' . $block->getAccountName()) ?>">
                <?= $block->escapeHtml($block->getAccountName()) ?>
            </a>
        </h2>
        <div  class="slick-instagram-slider">
            <?php foreach ($block->getInstagramData() as $post) : ?>
                <div class="item">
                    <a target="_blank" href="<?= $block->escapeUrl($post['link']) ?>">
                        <img src="<?= $block->escapeUrl($post['image_src']) ?>" alt="<?= $block->escapeHtmlAttr($post['caption']) ?>"/>
                    </a>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
<?php endif; ?>

<script>
    require([
        'jquery',
        'slick'
    ], function ($) {

        'use strict';

        $(".slick-instagram-slider").slick(
            {
                dots: <?= $block->escapeJsQuote($helper->slickDots()) ?>,
                arrows: <?= $block->escapeJsQuote($helper->slickArrows()) ?>,
                infinite: true,
                speed: 1000,
                slidesToShow: 6,
                slidesToScroll: 4,
                autoplay: true,
                autoplaySpeed: 4000,
                responsive: [
                    {
                        breakpoint: 1024,
                        settings: {
                            slidesToShow: 4,
                        }
                    },
                    {
                        breakpoint: 768,
                        settings: {
                            slidesToShow: 3,
                        }
                    }
                ]
            }
        );
    });
</script>
